[package]
name = "sslang"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
crossterm = "0.29.0"
miette = { version = "7.2.0", features = ["fancy"] }
nom = "7.0"
ratatui = "0.29.0"
slotmap = "1.0.7"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
